Some tweaks

diff --git a/bin/latest-atom b/bin/latest-atom
--- a/bin/latest-atom
+++ b/bin/latest-atom
@@ -6,7 +6,7 @@ source "${0%/*}/../bash/functions.sh"
 if [ -d ~/code/atom ]; then
     cd ~/code/atom
 else
-    sudo dnf --assumeyes install make gcc gcc-c++ glibc-devel git-core libgnome-keyring-devel || fail "Installation of dependencies failed!"
+#    sudo dnf --assumeyes install make gcc gcc-c++ glibc-devel git-core libgnome-keyring-devel || fail "Installation of dependencies failed!"
     cd ~/code/
     git clone git@github.com:Locke23rus/atom.git
     cd ~/code/atom
@@ -16,5 +16,6 @@ fi
 git fetch upstream || fail "Fetching of upstream failed!"
 git rebase upstream/master || fail "Rebase to upstream/master failed!"
 
-./script/build || fail "Build of Atom filed!"
-./script/grunt install --install-dir ~/.local || fail "Installation of Atom failed"
+# ./script/build || fail "Build of Atom filed!"
+# ./script/grunt install --install-dir ~/.local || fail "Installation of Atom failed"
+./script/build --install-dir ~/.local --install || fail "Build and install of Atom filed!"
